spring.application.name=med-lab-final
spring.datasource.url=jdbc:mysql://localhost:3306/test_lab
spring.datasource.username=root
spring.datasource.password=11111111
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=medlab.servicemail@gmail.com
spring.mail.password=nmvollqwpmwnaopo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

server.port=8080

logging.file.name=medlab.log
logging.level.org.javarush.medlabfinal=INFO